Allow tests to pass with or without cross-origin start pages
We have recently removed the static start pages in pre-production, but this means that smoke tests are failing because the "cy.origin" block errors if the specified origin is the same domain as the top:
   CypressError: `cy.origin()` requires the first argument to be a different domain than top.

To fix this requires some duplication of test steps - i attempted to extract these to functions to avoid the replication, but the problem then is that the functions aren't available to call from within the cy.origin code block.